version: "3.1"

services:
  react:
    build: .
    ports:
      - "3000:3000"
    networks:
      - contact-sys-network

networks:
  contact-sys-network:
    external:
      name: contact-sys-network
